---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Get own IP
  become: no            #Don't run this with sudo
  ipify_facts:
  connection: local     #Run this on the local machine

- name: Copy main nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: '0644'

- name: Ensure streamcfg directory exists
  file: 
    path: /etc/nginx/streamcfg
    state: directory

- name: Setup nginx reverse proxy (https only)
  template:
    src: reverse_proxy.conf.j2
    dest: /etc/nginx/streamcfg/reverse_proxy.conf
    owner: root
    mode: '0644'
  register: nginx_cfg

- name: Restart Nginx if needed
  service:
    name: nginx
    state: restarted
  when: nginx_cfg.changed

